[package]
name = "significance-clustering"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.5.1"
itertools = "0.10.3"
hashbrown = { version = "0.12.0", features = ["rayon", "inline-more"] }
